# Site settings
title: No Binding Press
email: contact@nobindingpress.com

description: > # this means to ignore newlines until "baseurl:"
  No Binding Press makes beautiful e-ditions of classic works. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nobindingpress.com"

homepage_categories:
  - id: shakespeare
    heading: Shakespeare Editions

stores:
  gplay:
    name: Google Play
    icon: img/gplay.png

collections:
  books:
    output: true
    permalink: /books/:title/

defaults:
  -
    scope:
      path: ""
      type: books
    values:
      layout: book


# Build settings
markdown: kramdown
